config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'trending' => 'static_pages#trending'
  
  get 'landing' => 'static_pages#landing'

  get 'profile' => 'static_pages#profile'

  get 'home' => 'static_pages#home'

  get 'inbox' => 'static_pages#inbox'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing
      render :layout => false
  end

  def home
  end

  def profile
  end

  def newsfeed
  end

  def inbox
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_audioplayer.html.erb
<div class = "audioplayer-bottom">
	<div class = "audioplayer-image">
	</div>
	<div class = "audioplayer-info">
		<h4> Artist Name </h4> <br> Song Name 
	</div>


	<div class = "audioplayer-play">
		<span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span>
		<span class="glyphicon glyphicon-play" aria-hidden="true"></span>
		<span class="glyphicon glyphicon-step-forward" aria-hidden="true"></span>
	</div>
	


	<div class="progress">
		<div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
			<span class="sr-only">60% Complete</span>
		</div>
	</div>


	<div class = "audioplayer-length">
		2:32 / 4:30
	</div>

	<div class = "audioplayer-repeat">
		<span class="glyphicon glyphicon-retweet" aria-hidden="true"></span>
		<span class="glyphicon glyphicon-random" aria-hidden="true"></span>
	</div>

	<div class = "audioplayer-volume">
		<span class="glyphicon glyphicon-volume-up" aria-hidden="true"></span>

		<div class="progress">
		<div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
			<span class="sr-only">60% Complete</span>
		</div>
		</div>
	</div>



  </div>





</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">

    <div class = "logobox">
    <%= link_to "", '#', id: "logo" %>
   	</div>

   	<div class = "logobox2">
    <%= link_to "Discover", 'trending', id: "logo2" %>
   	</div>
			<div class ="header-login-username">
			</div>
			<div class ="header-login-password">
			</div>
			
		<%= link_to home_path do %>
			<div class ="loginbox"> Log In
			</div>
		<% end %>

  
</header>

app/views/layouts/_leftCol.html.erb
<div class = "leftCol">


<%= link_to landing_path do %>
	<div class = "logobox">
   	</div>
<% end %>

	<div class = "leftBox3">
		<%= link_to profile_path do %>
			<div class ="leftBox-profile"></div>
		<% end %>

		<div class ="leftBox-profile-name"> <%= link_to "Profile" , profile_path %></div>


	</div>

	<hr>

	<%= link_to home_path do %>
		<div class = "leftBox2"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>Home
		</div>
	<% end %>

	<%= link_to home_path do %>
		<div class = "leftBox2"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>Search
		</div>
	<% end %>

	<%= link_to trending_path do %>
		<div class = "leftBox2"><span class="glyphicon glyphicon-headphones" aria-hidden="true"></span>Trending
		</div>
	<% end %>

	<hr>

	<%= link_to home_path do %>
		<div class = "leftBox2"><span class="glyphicon glyphicon-expand" aria-hidden="true"></span>Playlists
		</div>
	<% end %>

	<%= link_to home_path do %>
		<div class = "leftBox2"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>Favourites
		</div>
	<% end %>

	<hr>

	<%= link_to inbox_path do %>
		<div class = "leftBox2"><span class="glyphicon glyphicon-headphones" aria-hidden="true"></span>Inbox
		</div>
	<% end %>

	<%= link_to inbox_path do %>
		<div class = "leftBox2"><span class="glyphicon glyphicon-headphones" aria-hidden="true"></span>Notifications</div>
	<% end %>


	<hr>

</div>

app/views/layouts/_rightCol.html.erb
<div class = "rightCol">
      <div class = "rightbox">
      </div>

</div>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/_singleplayer.html.erb
		<div class = "singleplayer">
			<div class ="single-songimage">
			</div>


				
			<div class ="singleplayer-rightCol">
				<div class ="singleplayer-genre">
					Hip Hop
				</div>

				<div class ="singleplayer-time"> 2:32 / 3:30
				</div>

			</div>

			<div class ="single-songinfo">
				<span class="glyphicon glyphicon-play-circle" aria-hidden="true"></span>
				<div class ="single-songinfo-name"> <h4> Artist Name </h4>

					<br> Song Name
				</div>

				<div class="progress">
					<div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
						<span class="sr-only">60% Complete</span>
					</div>
				</div>

				<div class ="single-songinfo-stats">

				<div class = "single-play">
					<span class="glyphicon glyphicon-play" aria-hidden="true"></span>10k
				</div>
				<div class = "single-play2">
					<span class="glyphicon glyphicon-star" aria-hidden="true"></span>20k
				</div>
				<div class = "single-play2">
					<span class="glyphicon glyphicon-retweet" aria-hidden="true"></span>30k
				</div>
				<div class = "single-play2">
					<span class="glyphicon glyphicon-comment" aria-hidden="true"></span>40
				</div>



				</div>

			</div>

		</div>

app/views/layouts/_songplayer.html.erb
	<div class = "songplayer">
		
		<div class = "songplayer-header">
			<div class = "songplayer-header-type">Songs 
			</div><div class = "songplayer-vr"></div>

			<div class = "songplayer-header-type">Albums
			</div><div class = "songplayer-vr"></div>

			<div class = "songplayer-header-type">Playlists
			</div><div class = "songplayer-vr"></div>

	
		</div>

		<div class = "playerinfo">


			<div class ="songimage">
			</div>


			<div class ="songinfo">	
				<h4> Artist Name </h4><br>
				Buy 1 Get 3 Free! Select 3 Commercial, WAV-Trackout or Unlimited Leases for discount to apply automatically - www.thechasebeats.com
			</div>


			<div class ="buyinfo">
				<h2>Items:
				<br>
				Total:
				</h2>

				<a href="#" class ="buyinfo-button button-class"> Buy Now
				</a>


			</div>

		</div>

	<div class = "song-section">

		<%= render 'layouts/songplayersingle' %>
		<%= render 'layouts/songplayersingle' %>
		<%= render 'layouts/songplayersingle' %>
		<%= render 'layouts/songplayersingle' %>
		<%= render 'layouts/songplayersingle' %>
		<%= render 'layouts/songplayersingle' %>
		<%= render 'layouts/songplayersingle' %>
		<%= render 'layouts/songplayersingle' %>
		<%= render 'layouts/songplayersingle' %>
		<%= render 'layouts/songplayersingle' %>
		<%= render 'layouts/songplayersingle' %>
		<%= render 'layouts/songplayersingle' %>
								




	</div>

</div>

app/views/layouts/_songplayersingle.html.erb
<div class = "song">

	<div class ="song-name">
		<div class ="song-name-image">
		</div>
		Song Name
		<div class ="song-name-price">
		$24.95 - $149.95
		</div>

	</div>
	
	<div class ="song-add">
		<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Everest </title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
  

  </head>
  <body>

	<%= render 'layouts/leftCol' %>

<!--<%= render 'layouts/audioplayer' %>-->

<div class ="centerCol">
  
      <%= yield %>
</div>

  </body>
</html>

app/views/static_pages/home.html.erb
<div class ="post-section">


		<div class = "newsfeed-header">Posts
		</div>


		<%= render 'layouts/singleplayer' %>


		<%= render 'layouts/singleplayer' %>


		<%= render 'layouts/singleplayer' %>


		<%= render 'layouts/singleplayer' %>


		<%= render 'layouts/singleplayer' %>


		<%= render 'layouts/singleplayer' %>


		<%= render 'layouts/singleplayer' %>


		<%= render 'layouts/singleplayer' %>
		

		<%= render 'layouts/singleplayer' %>

</div>

app/views/static_pages/inbox.html.erb
<div class = "inbox">

		<div class = "inbox-leftCol">
			<div class = "inbox-leftCol-top">
				<div class ="privatebox"> Private
				</div>
				<div class ="openbox"> Open
				</div>
			</div>

			<div class ="inbox-leftCol-bottom">


				<div class ="messagebox">
				</div>
				<div class ="messagebox">
				</div>
				<div class ="messagebox">
				</div>
				<div class ="messagebox">
				</div>
				<div class ="messagebox">
				</div>
				<div class ="messagebox">
				</div>
				<div class ="messagebox">
				</div>
				<div class ="messagebox">
				</div>
				<div class ="messagebox">
				</div>
				<div class ="messagebox">
				</div>
				<div class ="messagebox">
				</div>
				<div class ="messagebox">
				</div>

			</div>


		</div>


		<div class = "inbox-rightCol">
			<div class = "inbox-rightCol-top">
				<div class ="newmessage"> New Message
				</div>
			</div>
			<div class = "inbox-rightCol-middle">
			</div>


			<div class = "inbox-rightCol-bottom">
				<div class = "send-message">
				</div>

			</div>

		</div>







</div>

app/views/static_pages/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Everest </title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>

  </head>
  <body>

	<%= render 'layouts/header' %>
<div class ="landing-background">



	<div class ="landing-signup">
		
		<div class ="landing-signup-text"> New to Boost? Sign up 
		</div>

		<hr>

		<div class ="landing-signup-form">
	

			<div class ="landing-signup-fullname">
			</div>

			<div class ="landing-signup-email">
			</div>

			<div class ="landing-signup-password">
			</div>

			<div class ="landing-signup-username">
			</div>

			<div class ="landing-signup-button"> Sign Up
			</div>

		</div>

	</div>











</div>


</div>

  </body>
</html>

app/views/static_pages/profile.html.erb
<div class = "profile-head">
	<div class = "profile-picture">
	</div>

	<div class = "profile-name">
	Artist Name
	</div>


	<div class = "coverpicture">
	</div>

	<div class = "profile-menubar">

			<div class = "songplayer-header">
			<div class = "songplayer-vr"></div>

			<div class = "songplayer-header-type">About
			</div><div class = "songplayer-vr"></div>

			<div class = "songplayer-header-type"><h5> 56</h5> Songs
			</div><div class = "songplayer-vr"></div>


			<div class = "songplayer-header-type"><h5> 324 </h5>Following
			</div><div class = "songplayer-vr"></div>

			<div class = "songplayer-header-type"><h5> 50k </h5>Followers
			</div><div class = "songplayer-vr"></div>

			<div class = "songplayer-header-type"><h5> 932 </h5>Favourites
			</div><div class = "songplayer-vr"></div>
	
	
		</div>

	</div>
</div>

		<%= render 'layouts/songplayer' %>

<div class ="post-section">

		<div class = "newsfeed-header">Posts
		</div>

		<%= render 'layouts/singleplayer' %>


		<%= render 'layouts/singleplayer' %>


		<%= render 'layouts/singleplayer' %>


		<%= render 'layouts/singleplayer' %>

</div>

app/views/static_pages/trending.html.erb
	<div class = "trending">

		<div href = "/profile" class = "featurebox">
		</div>

		<!--Song Row 1-->

		<div class = "songbox">
		</div>

		<div class = "songbox">
		</div>


		<div class = "songbox">
		</div>


		<div class = "songboxb">
		</div>

		<!--Song Row 2-->


		<div class = "songbox">
		</div>

		<div class = "songbox">
		</div>


		<div class = "songbox">
		</div>


		<div class = "songboxb">
		</div>


		<!--Song Row 3-->


		<div class = "songbox">
		</div>

		<div class = "songbox">
		</div>


		<div class = "songbox">
		</div>


		<div class = "songboxb">
		</div>

	</div>